import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import 'public/assets/bootstrap/css/bootstrap.min.css'
import 'public/assets/css/Nunito.css'
import 'public/assets/fonts/fontawesome-all.min.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
